### ISSUE TITLE
Filter for minors is not correctly implemented

### ISSUE THREAD

**Issue by fxcoudert** [minutis-redcall/redcall#694]
A filter for minors was implemented in https://github.com/minutis-redcall/redcall/issues/197 but it is not fully working. It appears the Redcall database extracts the birth year from Pegass, but not the full date. So volunteers in the year of their 18th birthday are not filtered out, even if they are still minors.

A volunteer whose birth date in Pegass is 10/12/2005, has birth date of 01/01/2005 in Redcall. He is triggered by default, despite being still minor.

**Comment by ninsuo** [comment]
Hi FX,

Thank you for the notice.

Indeed, since a GDPR audit that happened last December, we do not have access to full birthdays anymore, but we have access to a "minor" flag instead. 

The implementation is still wrongly using the birthday field. 
Will provide a fix tomorrow.

Cheers

**Comment by ninsuo** [comment]
211f5ca9942d32ec88cbe931b0dfb97a6baca464 should fix the issue.
It will take up to 2 hours to have data correctly updated on the database, in the meantime I've put a message at the top of the app.
Cheers
