### ISSUE TITLE
Fix language selection

### ISSUE THREAD

**Issue by GuiguiWeb** [minutis-redcall/redcall#697]
Hello !

Scenario: If we change the language, it is not possible to return to French.
Hypothesis : app.request.locale does not behave as expected

![screencapture-redcall-minutis-croix-rouge-fr-space-3e581425-580a-4f2b-bef3-335bb763c426-2023-05-06-16_02_33](https://user-images.githubusercontent.com/26392178/236628936-bcf4995d-0ca1-4924-b24f-8a0b9e8d7990.png)

Best regards,
Guillaume

**Comment by ninsuo** [comment]
Hi Guillaume,
Thanks for your report.
I was not able to reproduce (either locally or on the server-side), so I just make all locales appear at the bottom.
See you.
A
